# Generated by Django 4.2.2 on 2023-06-11 06:50

from django.db import migrations, models
import django.db.models.deletion
import meropasal.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('product_img_url', models.ImageField(upload_to=meropasal.models.get_image_path, verbose_name='Product image')),
                ('product_img_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meropasal.category')),
            ],
        ),
    ]
