# Generated by Django 4.2.2 on 2023-06-12 11:31

from django.db import migrations, models
import django.db.models.deletion
import meropasal.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blog_name', models.CharField(max_length=100, verbose_name='Name')),
                ('blog_description', models.TextField(max_length=1000, verbose_name='Description')),
                ('blog_img_url', models.ImageField(upload_to=meropasal.models.get_blog_image_path, validators=[meropasal.models.validate_image_file_extension], verbose_name='Blog image')),
                ('blog_img_name', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=100, verbose_name='Name')),
                ('contatc_email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('contact_message', models.TextField(max_length=1000, verbose_name='Message')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('product_img_url', models.ImageField(upload_to=meropasal.models.get_product_image_path, validators=[meropasal.models.validate_image_file_extension], verbose_name='Product image')),
                ('product_img_name', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('stock', models.IntegerField(null=True, verbose_name='Stock')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meropasal.category')),
            ],
        ),
    ]
