# Generated by Django 4.2.2 on 2023-06-11 10:18

from django.db import migrations, models
import meropasal.models


class Migration(migrations.Migration):

    dependencies = [
        ('meropasal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img_name',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img_url',
            field=models.ImageField(upload_to=meropasal.models.get_image_path, validators=[meropasal.models.validate_image_file_extension], verbose_name='Product image'),
        ),
    ]
