# Generated by Django 4.2.2 on 2023-06-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meropasal', '0002_keyfeatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_img_name',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='features',
            field=models.TextField(max_length=1000),
        ),
    ]
