# Generated by Django 4.2.2 on 2023-06-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meropasal', '0003_alter_blogs_blog_img_name_alter_blogs_blog_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_description',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
    ]
